server:
  port: 8081

spring:
  application:
    name: user

  config:
    import: "classpath:application-core.yml"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
