version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD : 123456
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/:/var/lib/mysql  # 데이터베이스 데이터를 저장할 호스트의 디렉토리 설정

  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"