version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456  # root 사용자의 비밀번호 설정
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./data/:/var/lib/mysql  # 데이터베이스 데이터를 저장할 호스트의 디렉토리 설정

  cache-database:
    image: redis
    container_name: spring_cache
    expose:
      - 6379
    ports:
      - "6379:6379"