version: '3.8'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_started
    ports:
      - "8080:8080"
  db:
    image: mysql:8.0
    container_name: mysqldb-server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER : root
      MYSQL_ROOT_PASSWORD : 123456
      MYSQL_DATABASE: mymarket