server:
  port: 8084

spring:
  application:
    name: order-service

  config:
    import: "classpath:application-core.yml"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka