server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  application:
    name: gateway

  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true

      routes:
        - id: user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/join, /api/auth/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Authorization

        - id: user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: user
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: order
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/items/**

        - id: order
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**

        - id: stock
          uri: lb://STOCK-SERVICE
          predicates:
            - Path=/api/stocks/**