spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
        show_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/mymarket
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379

#jwt
jwt:
  secret: mymarkeysecretkey